### ISSUE TITLE
AttributeError: 'GPT2LMHeadModel' object has no attribute 'predict'

### ISSUE THREAD

**Issue by scy6500** [hyunwoongko/openchat#30]
![스크린샷 2021-04-21 오전 10 48 58](https://user-images.githubusercontent.com/55119006/115490988-196a6b00-a29a-11eb-809d-511af7efdd22.png)
    

    /usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
        946                 return modules[name]
        947         raise AttributeError("'{}' object has no attribute '{}'".format(
    --> 948             type(self).__name__, name))
        949 
        950     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:
    
    AttributeError: 'GPT2LMHeadModel' object has no attribute 'predict'
When I select dialogpt and chat, I get the error

**Comment by hyunwoongko** [comment]
I fixed this bug.
Could you try again?
`pip install --upgrade openchat`
