### ISSUE TITLE
gpt neo medium model not available.

### ISSUE THREAD

**Issue by fpem123** [hyunwoongko/openchat#31]
<img width="908" alt="스크린샷 2021-04-23 오후 2 52 53" src="https://user-images.githubusercontent.com/27391246/115824910-a997e400-a443-11eb-97b6-5a46ea986a98.png">

When I use gptneo.medium, I get the error.

So I entered the [Huggigface](https://huggingface.co/EleutherAI), and it seems that the medium model EleutherAI/gpt-neo-350M has gone down.

**Comment by hyunwoongko** [comment]
What is your transformers version?

**Comment by ibivibiv** [comment]
The Huggingface GPT Neo Medium was removed.  EleutherAI has pulled this model.

**Comment by hyunwoongko** [comment]
This model is currently not available. Please use another model.
