### ISSUE TITLE
ImportError: cannot import name 'BlenderbotSmallForConditionalGeneration' from 'transformers' (/opt/conda/lib/python3.8/site-packages/transformers/__init__.py)

### ISSUE THREAD

**Issue by detuvoldo** [hyunwoongko/openchat#4]
Hello,

Thanks for releasing your work. When trying to import openchat, I found this error. I think it is because `transformers` library did not support `BlenderbotSmallForConditionalGeneration` anymore. Do you have any ideas for that?

**Comment by hyunwoongko** [comment]
What version of you transformers?

**Comment by detuvoldo** [comment]
I'm using 4.3.3, It satisfies the requirements in the installation

**Comment by hyunwoongko** [comment]
Ok. I see. 
I'll change requirements.
thanks!

**Comment by detuvoldo** [comment]
Thanks for your quick response.
