### ISSUE TITLE
After several turns, Blenderbot throw Index ErrorL index out of range in self

### ISSUE THREAD

**Issue by shimazing** [hyunwoongko/openchat#9]
![image](https://user-images.githubusercontent.com/12490314/110427396-071dde80-80eb-11eb-9b52-2fe82e543f76.png)

While running Blenderbot large, IndexError occurs in torch after a few turns. 
Is it due to the constraint for the maximum length of contexts??

**Comment by woomurf** [comment]
Did you solve the problem? If you solved it, could you share the solution?

**Comment by hyunwoongko** [comment]
I'm sorry for the late response.
Could you show me the conversation script where the error occurred?
I will find a solution after reproducing the error.

**Comment by fpem123** [comment]
<img width="1259" alt="스크린샷 2021-03-09 오후 4 14 17" src="https://user-images.githubusercontent.com/27391246/110434895-b65fb300-80f5-11eb-99a1-85fbc7f9c485.png">

I am getting the same error as this. Occurred when sending a message using the same user_id over and over again.

**Comment by shimazing** [comment]
I think the error occurs when the length of dialogue history +  user input if larger than self.max_contex_length. In line 90 blenderbot.py, num_of_stacked_token is checked to be less than max_context_length but this condition is not enough because (# of input tokens + num_of_stacked_token) can be larger than self.max_context_length.

**Comment by hyunwoongko** [comment]
I redesign logic. please check new version :)
